{% set name = "zenodo_get" %}
{% set version = "2.0.0" %}
{% set python_min = "3.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zenodo_get-{{ version }}.tar.gz
  sha256: 9e17e35b0655f4a1ccbb1c3c9c4d0a7a79a5bdb0ff7d1ee28d5581f69cdc6312

build:
  number: 0
  noarch: python
  entry_points:
    - zenodo_get = zenodo_get.zget:cli
  script: {{ PYTHON }} -m uv pip install . -vv

requirements:
  host:
    - uv
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - requests
    - python-wget
    - humanize
    - click

test:
  imports:
    - zenodo_get
  commands:
    - pip check
    - zenodo_get --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dvolgyes/zenodo_get
  summary: Zenodo_get - a downloader for Zenodo records
  license: AGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - casperdcl
    - ickc
