{% set name = "zenodo_get" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zenodo_get-{{ version }}.tar.gz
  sha256: 7af8580d34ef4e89872c8570eb1445b80048cb0f5efabd1485914c479eef8ea9

build:
  number: 0
  noarch: python
  entry_points:
    - zenodo_get = zenodo_get.zget:zenodo_get
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests
    - python-wget
    - humanize

test:
  imports:
    - zenodo_get
  commands:
    - pip check
    - zenodo_get --help
  requires:
    - pip

about:
  home: https://gitlab.com/dvolgyes/zenodo_get
  summary: Zenodo_get - a downloader for Zenodo records
  license: AGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - casperdcl
    - ickc
