{% set name = "zenodo_get" %}
{% set version = "1.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zenodo_get-{{ version }}.tar.gz
  sha256: 2303972f18fc47bccded983f9f4639011e1a5870c4d388935535e229aaae9012

build:
  number: 0
  noarch: python
  entry_points:
    - zenodo_get = zenodo_get.zget:zenodo_get
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests
    - python-wget

test:
  imports:
    - zenodo_get
  commands:
    - pip check
    - zenodo_get --help
  requires:
    - pip

about:
  home: https://gitlab.com/dvolgyes/zenodo_get
  summary: Zenodo_get - a downloader for Zenodo records
  license: AGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ickc
