{% set name = "zenodo_get" %}
{% set version = "3.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/zenodo_get-{{ version }}.tar.gz
  sha256: 73c945198853aa362cf8ce6a71b9f1112671ce995622a1969978ffdf12ecd10f

build:
  number: 0
  noarch: python
  entry_points:
    - zenodo_get = zenodo_get.zget:zenodo_get
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - requests
    - python-wget
    - humanize

test:
  imports:
    - zenodo_get
  commands:
    - pip check
    - zenodo_get --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/dvolgyes/zenodo_get
  summary: Zenodo_get - a downloader for Zenodo records
  license: AGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - casperdcl
    - ickc
